export const EXAMPLE_PATH = 'blog-starter'
export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL = 'https://ik.imagekit.io/wphcyip3g/racoelho_dev/1688439289672.jpeg?updatedAt=1701730648991'
export const BLOG_NAME = 'Racoelho'
export const KEYWORDS = 'dev, blog, tech, tecnologia, programador, programação, developer'
export const DESCRIPTION = 'Blog pessoal do Rafael Coelho'
export const AUTHOR = 'racoelho'
export const LANG = 'pt-BR'
export const GITHUB_REPO = 'https://github.com/rafa-coelho'
