name: Update Version

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - main

jobs:
  update-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Update version and build date
        run: |
          # Incrementa a versão usando npm version (sem criar tag Git)
          npm version patch --no-git-tag-version
          
          # Atualiza a data de build para hoje
          TODAY=$(date +%Y-%m-%d)
          
          # Lê a versão atualizada
          VERSION=$(node -p "require('./package.json').version")
          
          # Atualiza a data de build
          jq ".buildDate = \"$TODAY\"" package.json > package.json.tmp
          mv package.json.tmp package.json
          
          echo "Versão atualizada: $VERSION (data: $TODAY)"
      
      - name: Commit and push changes
        run: |
          git add package.json
          git commit -m "chore: bump version [skip ci]"
          git push origin HEAD:${GITHUB_REF#refs/heads/} 